### ISSUE TITLE
descrizioni delle feature  B, livello, trange

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/cosudo#1]
Abbiamo trovato  le "descrizioni" delle feature  B, livello, trange ecc in diversi file javascript, vorremmo evitare di utilizzarli come mappe poiché ogni variazione/aggiunta di feature porterebbe inevitabilmente a modificare questi file.
Qualora questi risultino "immutabili" potremmo procedere come avete già fatto, in caso contrario vorremmo sapere se vi sono api o librerie che restituiscono tali descrizioni in alternativa?

**Comment by pat1** [comment]
Abbiamo presente il problema che era stato temporaneamente aggirato con mappe statiche riscritte in js.
Ho aperto una issue su dballe relativa alle API per avere l'elenco delle B, level, trange
https://github.com/ARPA-SIMC/dballe/issues/234

La fonte primaria per le B risulta questo file:
/usr/share/wreport/dballe.txt
distribuito con dballe
Ritengo la sua lettura diretta una soluzione non ottimale rispetto all'uso di API, tanto più che mi pare che le fonti originali di level e trange non siano accessibili.

Ritengo che sia apportuno prevedere una modalità di generazione automatica delle "mappe" utilizzabili da js e valutare se questa generazione automatica avvenga in fase di build del pacchetto o con modalità "run time" con opportuna cache.

Per non bloccare lo sviluppo suggerisco di iniziare ad utilizzare le mappe statiche, per poi migrare eventualmente a quelle dinamiche.

**Comment by fabiodepas** [comment]
Avevamo individuato il file "/usr/share/wreport/dballe.txt" poichè indicato nella documentazione, stiamo procedendo momentaneamente con le mappe json già presenti e con le utility create da voi, la build automatica delle mappe a questo punto potrebbe essere un buon compromesso per non attendere l'esposzione dei WS di dballe. Grazie.

**Comment by pat1** [comment]
come discusso in:
https://github.com/ARPA-SIMC/dballe/issues/234
l'unica possibilità è far generare un mappa in js per la tabella B al build di dballe che è la fonte primaria di tale tabella.
Non sono sicuro che tale tabella distribuita in /usr/share/dballe sia immediatamente utilizzabile da django.
Se questa strada è percorribile richiedo tale generazione in dballe.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
