### ISSUE TITLE
Permessi per aggiungere i secrets

### ISSUE THREAD

**Issue by fabiodepas** [ARPA-SIMC/cosudo#10]
Necessitiamo dell'acccesso con poteri magori per poter aggiungere i  secrets sugit nel  repository cosudo

**Comment by edigiacomo** [comment]
Pare servano i permessi di admin sul repository per aggiungere secrets: https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository

@pat1 come referente del progetto ti chiedo conferma prima di procedere.

**Comment by pat1** [comment]
visto che sono ignorante posso chiedere a cosa servono i secrets ?

**Comment by fabiodepas** [comment]
E' uno strumento messo a disposizione da git per archiviare password o chiavi di accesso in modo criptato, esempio per le chiavi di pyInstaller, poichèse fossero visibili a tutti, tutti bse ne potrebero appropriare ed  utilizzarle.
https://git-secret.io/

**Comment by pat1** [comment]
Grazie della risposta, ma nello specifico a cosa dovrebbero servire. Quali password dovreste memorizzare sul git pubblico?
