### ISSUE TITLE
Radarconverter - azzeramento precipitazioni

### ISSUE THREAD

**Issue by virginiapoli** [ARPA-SIMC/cosudo#103]
1) Nel testare il convertitore per la cumulata radar da netcdf a grib (e ritorno) ho verificato che le precipitazioni vengono azzerate (mentre dovrei avere una precipitazione massima pari a 23.75 mm). Allego file originario (comp-ACRR*.nc) e riconvertito (1200_riconvertito.nc)

Perchè la retroconversione sia perfetta, inoltre:
2) nel file riconvertito (da grib a netcdf) la variabile time è definita double, mentre nel file originario è float;
3) è comparsa una dimensione aggiuntiva ("idl") non presente nel file originario.

[1200_riconvertito.nc.gz](https://github.com/ARPA-SIMC/cosudo/files/6121732/1200_riconvertito.nc.gz)
[comp-ACRR_202009201200_001H.nc.gz](https://github.com/ARPA-SIMC/cosudo/files/6121733/comp-ACRR_202009201200_001H.nc.gz)

**Comment by virginiapoli** [comment]
Continuo ad aver problemi nella conversione in grib (punto 1). In output nel grib, continuo ad avere valori del campo di precipitazione nulli. 
  #-READ ONLY- maximum = 0;
  #-READ ONLY- minimum = 0;
  #-READ ONLY- average = 0;
  #-READ ONLY- numberOfMissing = 1431;
  #-READ ONLY- standardDeviation = 0;
  #-READ ONLY- skewness = 0;
  #-READ ONLY- kurtosis = 0;
  #-READ ONLY- isConstant = 1;
  #-READ ONLY- getNumberOfValues = 108170;

**Comment by fabiodepas** [comment]
Allego i file convertiti
[file_convertiti.zip](https://github.com/ARPA-SIMC/cosudo/files/6150407/file_convertiti.zip)
nello specifico  vi  era un  bug nel posizionamento dei dati dei grib2  e quasto impediva la visualizzazione su mappa.
Per quanto riguarda i dati mostrati ioconvertendo  il netcdf in grib2 visualizzo:
#-READ ONLY- maximum = 23.7487;
#-READ ONLY- minimum = 0;
#-READ ONLY- average = 0.208813;
#-READ ONLY- numberOfMissing = 1431;
#-READ ONLY- standardDeviation = 1.02357;
#-READ ONLY- skewness = 9.11572;
#-READ ONLY- kurtosis = 115.276;
#-READ ONLY- isConstant = 0;
#-READ ONLY- getNumberOfValues = 108170;

Aspetto conferma prima di richiudere.

**Comment by virginiapoli** [comment]
I file allegati sono corretti, ma non riesco a riprodurli.
Uso il convertitore da linea di comando (sbaglio qui qualcosa?):
python radar_netcdf2grib.py -i comp-ACRR_202009201200_001H.nc

Ho provato a verificare e prima del "codes_set_values(gaid_template, cum_pr_mm.flatten())" torna tutto. 
Dopo, anche rileggendo i valori con un codes_get_values ho che il massimo (diverso dal missing) è 0. 

La mia versione degli eccodes è 2.20.0

**Comment by fabiodepas** [comment]
Il comando è quello giusto, noi in realtà abbiamo testato la  procedura sia  con eccodes versione 2.16 sia con la 2.18,
la versione 2.20 non sembra  abbia  passato la  build e non ci permette di installarla  da copr, stiamo provando a scaricarla a  mano.

**Comment by brancomat** [comment]
A titolo informativo:
sto lavorando al build di eccodes 2.20 su centos 8 (che richiede una versione di cmake attualmente non disponibile su centos 8) e sarà disponibile direi entro la fine della settimana, se volete risparmiarvi il build manuale.
@virginiapoli: se vogliamo escludere la versione di eccodes dalle variabili puoi testare lo stesso comando su `otto.metarpa` che è una centos 8 con eccodes 2.18.

Non so se sia collegato, noto che la #105 è stata mergiata in master dopo i test di Virginia, può aver avuto un ruolo?

**Comment by fabiodepas** [comment]
In realtà se il problema è che nel grib i dati sono azzerati non penso che la #105 risolva questo problema, perchè nel nostro caso i dati del grib  sono  sempre diversi da  0 sia  prima che dopo la #105.
Se si ha la possibilità di testare la  nuova  release su 2.18 io  opterei per questa altimenti proviamoad installare a mano la  2.20.

**Comment by virginiapoli** [comment]
Su otto.metarpa (centos8, eccodes 2.18, nuova release) lo script muore per "Segmentation fault (core dumped)" nel momento in cui chiama codes_set_values.
Ho provato anche la release precedente e mi dà lo stesso problema.

**Comment by fabiodepas** [comment]
Abbiamo provato su un'altra macchina (centos8 e centos8-minimal) con eccodes 2.20 e tutto sembra funzionare, ecco  i comandi eseguiti:

```
#DOWNLOAD E RUN DOCKER CONTAINER DOCKER
docker pull centos
docker run -it -v ~/TEMP/:/TEMP centos:8

#ENTRATI NEL CONTAINER
dnf -y install epel-release
dnf install yum-plugin-copr
dnf copr enable simc/stable
dnf copr enable pat1/rmap
dnf -y install dnf-plugins-core
dnf config-manager --set-enabled powertools
dnf install python3-rmap python3-django-cors-headers python3-pyparsing python3-django-classy-tags arkimet dballe provami dballe-web python3-netcdf4 netcdf-fortran netcdf-fortran-devel
pip3 install eccodes==1.0.0

#ESEMPIO  D'USO
python3 /TEMP/radarconverter/radar_netcdf2grib/radar_netcdf2grib.py -i /TEMP/a.nc -o /TEMP/a.grib2
```
Naturalmente è solo una delle prove che abbiamo  fatto

**Comment by brancomat** [comment]
La versione dei repository di sistema di pyhon3-eccodes è la 0.9.4-5, riuscite a provare con quella? (senza il `pip3 install`)

Comunque mi attrezzo per integrare in `simc/stable` una versione di python3-eccodes più recente e aggiorno il server `otto` per vedere se cambia qualcosa (come avrete visto ora nei repo centos8 di simc/stable è presente eccodes 2.20)

**Comment by fabiodepas** [comment]
Il problema è con  la  release pyhon3-eccodes 0.9.4-5 quella consiglita da noi è la 1.0.0 perchè a partire dalla 0.9.9 il  "Segmentation fault (core dumped)" è stato risolto. Non dovesse essere possibile aggiornare la versione su copr cerchiamo un'altra strada.

**Comment by brancomat** [comment]
Ok, ho aggiornato il repo `simc/stable` e `otto.metarpa` a:
`eccodes-2.20.0-1.el8.x86_64`
`python3-eccodes-1.1.0-1.el8.x86_64`

lo script ora non segfaulta più, l'ho testato sia su CentOS 8 che su una Fedora 32 aggiornata alle stesse versioni di eccodes e python3-eccodes, un dump del grib risultante mi dice:
```
  #-READ ONLY- maximum = 23.7487;
  #-READ ONLY- minimum = 0;
  #-READ ONLY- average = 0.208813;
  #-READ ONLY- numberOfMissing = 1431;
  #-READ ONLY- standardDeviation = 1.02357;
  #-READ ONLY- skewness = 9.11572;
  #-READ ONLY- kurtosis = 115.276;
  #-READ ONLY- isConstant = 0;
  #-READ ONLY- getNumberOfValues = 108170;
```
Passo però la palla a @virginiapoli per una conferma definitiva.

**Comment by fabiodepas** [comment]
Ok perfetto, confermo, grazie mille, attendiamo news.

**Comment by virginiapoli** [comment]
Dopo gli aggiornamenti sono riuscita a riprodurre i campi corretti.
Ho rieseguito il test passando da netcdf a grib e ritorno. 
Al di là di alcune piccole discrepanze sulle cifre decimali delle variabili, che credo siano dovute fisicamente alla rappresentazione dei float nella macchina, **i valori di mesh_dim (che mi pare vengano ricalcolati) vengono troncati:
ORIGINALE:
 mesh_dim = 0.01264954, 0.008998871 ;
RICONVERTITO:
 mesh_dim = 0.01265, 0.009 ;**

Il file riconvertito viene correttamente interpretato dalle nostre procedure di grafica.

**Comment by fabiodepas** [comment]
Confermo  che il valore è inserito senza arrotondamento e poi viene arrotondato automaticamente  in fase di scrittura nel  file.
Chiudo questa  issue se  dovessero esserci altri errori relativi lo  stesso  topic possiamo riaprirla.
Grazie mille
