### ISSUE TITLE
i canali del satellite non sono visualizzabili separatamente

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/cosudo#108]
i dati del satellite sono visualizzati nell'elenco dei livelli visualizzabili tutti come "scaled radiance"

**Comment by gianpieropa** [comment]
Potresti inviarmi un file che non sia scaled radiance, perché quelli che abbiamo utilizzato noi hanno tutti all'interno come parametro "Scaled radiance"
Da grib dump di questo [file](https://github.com/ARPA-SIMC/qc_sample_data/blob/master/satellite/grib/MSG4_VIS006_20200223_1100.grib) : 
`name = Scaled radiance;`

**Comment by pat1** [comment]
il contenuto dei grib non si distingue solo dal campo "name".
Nel dataset di test di prova sono già presenti differenti canali:
https://github.com/ARPA-SIMC/qc_sample_data/tree/master/satellite/grib

questo dice che è un prodotto da satellite
productDefinitionTemplateNumber = 31 [Satellite product (grib2/tables/4/4.0.table) ]

e questo campo dice la lunghezza d'onda centrale del canale
```
  scaledValueOfCentralWaveNumber = 625000
  scaledValueOfCentralWaveNumber = 256410
  scaledValueOfCentralWaveNumber = 114943
```
se la distinzione viene fatta solo dal campo "name" il problema si replica anche con gli altri dataset perchè ad esempio la temperatura può essere presente a livelli differenti o da modelli differenti

**Comment by gianpieropa** [comment]
dovrei aver risolto in https://github.com/gianpieropa/skinnywms/commit/6d0a2266dc08ce5673ce6d4908dc163706c12c05
