### ISSUE TITLE
la barra di navigazione nel tempo risulta di difficile utilizzo

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/cosudo#109]
mancando di frecce per l'incremento quando i passi nel tempo risultano di pochi minuti è estremamente difficile da utilizzare.
Da discutere la possibilità di navigare a passi di una ora.
Quando è posizionata su * quali layer del WMS sono visualizzati ?

**Comment by gianpieropa** [comment]
Allora quando la barra è posizionata su asterisco dovrebbe utilizzare l'orario impostato nella ricerca (quello nella barra in alto a sinistra). Se anche quello è impostato su * non dovrebbe effettuare la richiesta. Al momento la effettua e anche #106 dipende da quello.
Provvedo ad inserire un controllo sull'orario nella ricerca.
Per l'utilizzo della barra del tempo al momento vengono caricati tutti i "tempi" all'interno della risposta. Ditemi voi se modificarlo caricando un solo "tempo" per orario.

**Comment by pat1** [comment]
mi pare chiusa
