### ISSUE TITLE
 copia url: non copia protocollo e hostname

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/cosudo#111]
la copia della url per estrazione dati è monca

**Comment by gianpieropa** [comment]
La copia dell'url dipende dall'url "BORINUD_URL" nei settings, impostandolo ad un url completo  invece che "/borinud/...", anche nella copia sarà completo. Potreste risolvere in questo modo o altrimenti se lo ritenete necessario implemento un controllo che verifichi se sia presente o meno il  protocollo e il domino.

**Comment by pat1** [comment]
a parte che potrebbe essere un href in nuova finestra io nei template uso {{site.domain}}
del tipo :
<a href="//{{site.domain}}/insertdata/newstation">{% trans "Register a new station" %}</a>

https://docs.djangoproject.com/en/3.2/ref/contrib/sites/
```
In the syndication framework, the templates for title and description automatically have access to a variable {{ site }}, which is the Site object representing the current site. Also, the hook for providing item URLs will use the domain from the current Site object if you don’t specify a fully-qualified domain.
```
non so se è un suggerimento utile

**Comment by gianpieropa** [comment]
Si certo era per non utilizzare un'ennesima variabile globale dato che la funzione di copia è relativa ad un file js. Provvederò ad effettuare il fix. Per il comportamento indicatemi voi cosa preferite se una nuova finestra o semplicemente la copia dell'url.

**Comment by gianpieropa** [comment]
Ho risolto aggiungendo dominio e protocollo, se ci sono cambiamenti da effettuare per il comportamento della copia dell'url, riaprite tranquillamente l'issue.
