### ISSUE TITLE
mapserver error: Projection library error. proj error

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/cosudo#112]
Seguendo le istruzioni di installazione
alla richiesta:

http://test.rmap.cc/wms/mapserver/wms?service=WMS&request=GetCapabilities

ottengo:

msProcessProjection(): Projection library error. proj error "no arguments in initialization list" for "init=EPSG:3857"

**Comment by fabiodepas** [comment]
La versione di proj-devel è maggiore uguale di 5.2.0?

**Comment by pat1** [comment]
rpm -q proj
proj-6.3.2-4.el8.x86_64
E' quella di default come da specifiche per Centos 8
http://osgeo-org.1560.x6.nabble.com/Projection-library-error-td5409817.html

**Comment by fabiodepas** [comment]
Abbiamo eseguito alcuni  test, sembra sia dovuto a proj-devel, oltre proj è installato anche proj-devel?

**Comment by pat1** [comment]
installato proj-devel, stesso errore

**Comment by fabiodepas** [comment]
Stiamo effettuando i test su diverse macchine, su centos 8 minimal e base non da problemi,  su doker stiamo riscontrando solo che non vuole saperne di trovare (da solo, se loinstalliamo a  mano  funziona) il pacchetto "libarchive" ed anche su altre varianti.
Il problema in realtà sembra essere che mapserver non trova la cartella di proj, difatti una soluzione potrebbe essere linkarla a mano nel MAPFILE, ad esempio:
```
MAP
CONFIG "PROJ_LIB" "dir-di-proj"
```
nei nostri test è bastato installare la devel di proj (che in realtà era presente anche nel file spec creato da voi in passato ed  usato come modello  per la nuova versione di mapserver ) per risolverlo. Che versione specifica di centos avete? Ll'installazione è stata fatta seguendo https://github.com/ARPA-SIMC/cosudo/tree/master/guide?

**Comment by pat1** [comment]
Io utilizzo:

rpm -qi mapserver
Name        : mapserver
Version     : 7.2.2
Release     : 2.git7fe9b2b.el8
Architecture: x86_64
Install Date: mer 02 dic 2020 10:42:49 CET
Group       : Unspecified
Size        : 255073
License     : BSD
Signature   : RSA/SHA1, mar 16 giu 2020 12:39:39 CEST, Key ID a9137d5448628f8d
Source RPM  : mapserver-7.2.2-2.git7fe9b2b.el8.src.rpm
Build Date  : mar 16 giu 2020 12:39:31 CEST
Build Host  : ip-172-30-2-132.ec2.internal
Relocations : (not relocatable)
URL         : http://www.mapserver.org
Summary     : Environment for building spatially-enabled internet applications
Description :
Mapserver is an internet mapping program that converts GIS data to
map images in real time. With appropriate interface pages,
Mapserver can provide an interactive internet map based on
custom GIS data.

che è la versione disponibile:
https://copr.fedorainfracloud.org/coprs/simc/stable/package/mapserver/

mentre nella documentazione vedo citata la versione 7.6.1

Quale versione utilizzate nei vostri test?

**Comment by pat1** [comment]
Nelle istruzioni viene richiesto di fare:
```
mkdir /tmp/ms_tmp/
mkdir /ms_tmp/
mkdir /data/
mkdir /data/mapserver_data/
mkdir /data/config/
mkdir /data/config/map/
```
mkdir /tmp/ms_tmp/ non può funzionare in quanto rimossa a ogni reboot
delle altre bisognerebbe capire a cosa servono per trovare la giusta collocazione e dove è possibile modificarne i path se necessario; aggiungere dei root path non è generalmente concesso su un server correttamente gestiti

**Comment by pat1** [comment]
ho generato il pacchetto di mapserver alla versione 7.6.3, ma nulla pare essere cambiato
```
rpm -qi mapserver
Name        : mapserver
Version     : 7.6.3
Release     : 1
Architecture: x86_64
Install Date: mar 11 mag 2021 13:01:39 CEST
Group       : Unspecified
Size        : 255777
License     : BSD
Signature   : (none)
Source RPM  : mapserver-7.6.3-1.src.rpm
Build Date  : mar 11 mag 2021 13:01:22 CEST
Build Host  : rmap8-test.arpaepr.local
Relocations : (not relocatable)
URL         : http://www.mapserver.org
Summary     : Environment for building spatially-enabled internet applications
Description :
Mapserver is an internet mapping program that converts GIS data to
map images in real time. With appropriate interface pages,
Mapserver can provide an interactive internet map based on
custom GIS data.
```

**Comment by fabiodepas** [comment]
Potremmo avere  lo spec  file utilizzato? perchè la 7.6.3 non è quella del nostro spec, noi utilizziamo la 7.6.1.

Per quanto riguarda le directory "tmp" e "ms_tmp"  devono  essere accessibili dal web service (così come le cartelle  "data")

> The files generated by MapServer will be placed in the directory /tmp/ms_tmp/. The web server must be able to place files in this directory. The web server must make this directory available as /ms_tmp (if the web server is on www.ms.org, the web address to the directory must be: httpd://www.ms.org/ms_tmp/.

Come descritto in [https://mapserver.org/introduction.html#introduction-to-the-mapfile](https://mapserver.org/introduction.html#introduction-to-the-mapfile) 

Per le cartelle in "data", in "/data/config/map/" va il  mapfile e in "/data/mapserver_data/" i dati dei layer da leggere,
difatti nella guida abbiamo  specificato  di cambiare le directory, l'accorgimento che si può dare è che sia le cartelle "data" che le cartelle "tmp", o siano direttamente consultabili dal Web service oppure devono essere richiamate mediante comando:
`chcon -R -h -u system_u -r object_r -t httpd_sys_content_t "nome_cartella"` per renderle accessibili al web service

**Comment by pat1** [comment]
ho impostato correttamente le directory di lavoro e qui allego lo spec.
[mapserver.zip](https://github.com/ARPA-SIMC/cosudo/files/6459435/mapserver.zip)

**Comment by fabiodepas** [comment]
Il file "/usr/share/proj/proj.db" è presente? E' un  file SQLite e contiene le proiezioni, dovremmo controllare se contiene EPSG:3857, se  lo passate possiamo anche controllarlo  noi.
In caso EPSG:3857 non sia presente nel file, questo va sostituito con un file che la contiene.
In caso il file non sia presente bisogna individuare il  path d'installazione ed impostarlo manualmente nel mapfile con  
`CONFIG "PROJ_LIB" "dir-di-proj"`

**Comment by pat1** [comment]
```
ls -l /usr/share/proj/proj.db
-rw-r--r-- 1 root root 6234112 19 mag  2020 /usr/share/proj/proj.db
```
ed è quello ditribuito in Centos 8
```
rpm -qf /usr/share/proj/proj.db
proj-6.3.2-4.el8.x86_64
```
map.map contiene:
```
MAP
    CONFIG "PROJ_LIB" "/usr/share/proj/"
    CONFIG "PROJ_DEBUG" "ON"
    CONFIG "MS_ERRORFILE" "/tmp/ms_error.log"
    DEBUG 5
```

**Comment by fabiodepas** [comment]
Un test che  potrebbe essere utile per verificare  se è proj il problema, è quello di utilizzare proj esternamente, ad esempio con python, abbiamo installato pyproj==2.6  e dato i seguenti comandi:

```
from pyproj import CRS
crs = CRS.from_string("epsg:3857")
crs
```

Nel nostro caso funzioni  correttamente stampa le info della proiezione:
```
<Projected CRS: EPSG:3857>
Name: WGS 84 / Pseudo-Mercator
Axis Info [cartesian]:
- X[east]: Easting (metre)
- Y[north]: Northing (metre)
Area of Use:
- name: World - 85°S to 85°N
- bounds: (-180.0, -85.06, 180.0, 85.06)
Coordinate Operation:
- name: Popular Visualisation Pseudo-Mercator
- method: Popular Visualisation Pseudo Mercator
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich
```
Altrimenti potrebbe davvero essere un problema di permessi, dato che le uniche soluzioni che abbiaamo trovato riguardano  o la  directory del DB di  proj oppure i permesssi di esecuzione di mapserver che richiama proj.
Il vero problema in realtà è riemulare il medesimo errore, dato che abbiamo prova diverse istanze  anche in cloud.

**Comment by dcesari** [comment]
Forse questo [thread](http://osgeo-org.1560.x6.nabble.com/PROJ-Creating-projection-not-from-full-init-string-td5482194.html) che termina nelle fiamme può spiegare qualcosa? 

Ne capisco il giustio, ma paiono esserci differenze concettuali tra le varie versioni di proj.

**Comment by pat1** [comment]
```
dnf install python3-pyproj
python3
Python 3.6.8 (default, Aug 24 2020, 17:57:11) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyproj import CRS
>>> crs = CRS.from_string("epsg:3857")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/pyproj/datadir.py", line 99, in get_data_dir
    "Valid PROJ data directory not found."
pyproj.exceptions.DataDirError: Valid PROJ data directory not found.Either set the path using the environmental variable PROJ_LIB or with `pyproj.datadir.set_data_dir`.
Exception ignored in: 'pyproj._datadir.get_pyproj_context'
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/pyproj/datadir.py", line 99, in get_data_dir
    "Valid PROJ data directory not found."
pyproj.exceptions.DataDirError: Valid PROJ data directory not found.Either set the path using the environmental variable PROJ_LIB or with `pyproj.datadir.set_data_dir`.
>>> 
```
```
export PROJ_LIB=/usr/share/proj/
python3
Python 3.6.8 (default, Aug 24 2020, 17:57:11) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyproj import CRS
>>> crs = CRS.from_string("epsg:3857")
>>> crs
<Projected CRS: EPSG:3857>
Name: WGS 84 / Pseudo-Mercator
Axis Info [cartesian]:
- X[east]: Easting (metre)
- Y[north]: Northing (metre)
Area of Use:
- name: World - 85°S to 85°N
- bounds: (-180.0, -85.06, 180.0, 85.06)
Coordinate Operation:
- name: Popular Visualisation Pseudo-Mercator
- method: Popular Visualisation Pseudo Mercator
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

>>> 
```

**Comment by pat1** [comment]
@dcesari il problema sicuramente nasce dal cambio di API della versione 6 di proj, ma mapserver dovrebbe essere in grado di gestirle addirittura in modo automatico dalla versione 6.nonmiricordoquale. 
In più il parametro di configurazione CONFIG "PROJ_LIB" "/usr/share/proj/" dovrebbe esplicitare dove trovare le definizioni di proj.
Mi pare che qui il problema sia più su "trova le differenze" visto che abbiamo due istanze di mapserver su centos 8, una che va e una che non va. Forse meglio fare una sessione congiunta di verifica?

**Comment by fabiodepas** [comment]
Si, per noi la call sarebbe meglio di pomeiggio se possibile, ci proponete voi delle date?

**Comment by pat1** [comment]
c'era un errore di maiuscole/minuscole in map.map
