### ISSUE TITLE
Error: Login invalid/expired. Please visit https://copr.fedorainfracloud.org/api to get or renew your API token.

### ISSUE THREAD

**Issue by gianpieropa** [ARPA-SIMC/cosudo#117]
Sto avendo problemi a pubblicare la nuova build, durante l'esecuzione travis fallisce con il seguente errore

**Comment by edigiacomo** [comment]
Ho aggiornato il token. Inoltre, ho tolto il vincolo del deploy solo su tag, in modo che lo invii a Copr ad ogni commit: quest'ultimo scarica la versione indicata nello spec (https://github.com/ARPA-SIMC/cosudo/blob/v2/django-dynamic-map-borinud/django-dynamic-map-borinud.spec#L13). Quindi, fino a che la versione nello spec rimane uguale, ripacchettizza sempre la medesima versione (d'ora in poi la versione 2).
