### ISSUE TITLE
sincronizzazione grafici e vista mappa

### ISSUE THREAD

**Issue by PasqualiSIMC** [ARPA-SIMC/cosudo#118]
quando passo dalla vista mappa ai grafici perdo completamente l'informazione temporale di partenza

**Comment by gianpieropa** [comment]
è una funzionalità voluta, le due ricerche sono completamente separate. Una volta effettuata la ricerca su mappa se la si vuole su grafico bisogna effettuarla nella sezione grafico

**Comment by PasqualiSIMC** [comment]
Allora manca lo strumento con cui passare dalla visualizzazione spaziale a quella temporale fissando una stazione sulla mappa

**Comment by gianpieropa** [comment]
Per aggiungere una stazione con la relativa variabile (bcode, trange,level) al grafico basta cliccare sul bottone "add to graph" mostrato nell'immagine, dopo aver cliccato su un dato:
![Schermata del 2021-05-26 10-31-16](https://user-images.githubusercontent.com/68102511/119628932-d86ff400-be0d-11eb-8123-536ca40d0c76.png)
