### ISSUE TITLE
Lentezza caricamento dati osservati

### ISSUE THREAD

**Issue by PasqualiSIMC** [ARPA-SIMC/cosudo#124]
Abbiamo provato a caricare i dati di tutta italia di precipitazione di un giorno intero e cosudo ci ha messo 5 minuti di orologio.

**Comment by pat1** [comment]
a me ci mette 2 minuti per recuperare migliaia di stazioni offline; dopo averlo fatto una volta i dati rimangono in cache per 15 minuti.
Come dicevo il problema non è risolvibile con le tecnologie attuali e non è significativo dei tempi di utilizzo operativi che vede un set di dati molto limitato non offline.
Consiglio di usare un PC del pola e una connessione di rete veloce e portare pazienza visto che sono solo test per fare bug report.

**Comment by pat1** [comment]
ho risolto alcuni problemi e attuato alcuni trucchi per rendere più veloce il tutto simulando più o meno la situazione che sarà operativa
