### ISSUE TITLE
quale formato utilizzare per borinud (dbajson, jsonline, geojson) ?

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/cosudo#2]
* dbajson : json puro, immediatmente leggibile da js
* jsonline : non json puro, in alcuni casi fa risparmiare memoria
* geojson : json puro, immediatamente utilizzabile con alcune API js quali leaflet, ma al momento non include gli attributi e risulta più voluminoso

Bisogna decidere quale formato utilizzare e valutare se includere gli attributi in geojson.

**Comment by fabiodepas** [comment]
Abbiamo gia creato il parser delle jsonlin,  nei test effettuati questo codice sembra renderle leggibili correttamente:
```
//resp = jsonline dei summaries proveinente da borinud
resp = (JSON.parse("{\"j\":[" + resp.replaceAll(`}
{`,"}, {") + "]}")).j;
```
Che poi è la traduzione del vostro codice python: 
`json.dumps(self.jsondict(),default=json_serial)+"\n"`

Dato che l'utility di conversione l'abbiamo già realizzata, se effettivamente con jsonline si risparmia in fase di trasferimento meglio addossare al client questo piccolo onere di conversione. E' chiaro che i geojson sono decisamente più espressivi ma allo stesso tempo più pesanti ed in questo caso soprattutto per trasferimenti massivi, questo non giova alla causa.

**Comment by pat1** [comment]
con jsonline non si risparmia in trasferimento, se devo trasferire 100Mb di dati sempre 100Mb rimangono; è il client che in fase di elaborazione può lavorare in "stream" messaggio per messaggio, mentre dbajson necessita di 100Mb per memorizzare la risposta più tutto lo spazio per decodificare tutte le strutture e tenerle in memoria tutte.
La conversione che fate mi pare comporti solo oneri aggiuntivi al client per avere di fatto un dbajson che tanto vale richiedere ai WS direttamente da subito

**Comment by fabiodepas** [comment]
Allora anzichè tradurlo,  potremmo eseguire il parse riga per riga, resta inteso che un json seppure enorme a causa delle strutture di supporto, ha delle utility per agevolare le ricerche.
In alternativa per non scorrere continuamente tutta la risposta "testuale" potremmo utilizzare ad esempio un approccio posizionale:
-creare diverse liste, una per ciascuna feature
-ricercare nella prima lista la presenza di un valore e restituire gli indici
-sfruttare gli indici individuati per analizzare solo questi elementi nella seconda lista(feature)
-procedere con la terza e così  via fino ad ottenere solo  le combinazioni possibili
(Così diventa possibile anche risfruttare parzialmente le ricerche)
Naturalmente le liste occupano più spazio del testo, ma meno di un json enorme.
Non  so se questopotrebbe essere un buon compromesso in riferimento ai summariesad esempio.
Questo sempre sottintendendo che sarebbe meglio utilizzare un api che non restituisce tutto ma solo quanto di interesse.

**Comment by pat1** [comment]
> Allora anzichè tradurlo, potremmo eseguire il parse riga per riga, resta inteso che un json seppure enorme a causa delle strutture di supporto, ha delle utility per agevolare le ricerche.

io continuo ad essere dell'idea che qui jsonline non abbia nessuna utilità ...
l'unica differenza è che il server risponde con StreamingHttpResponse invece che con HttpResponse che gli fa risparmiare un po' di memoria, ma nei summaries poca poca

> In alternativa per non scorrere continuamente tutta la risposta "testuale" potremmo utilizzare ad esempio un approccio posizionale:-creare diverse liste, una per ciascuna feature -ricercare nella prima lista la presenza di un valore e restituire gli indici -sfruttare gli indici individuati per analizzare solo questi elementi nella seconda lista(feature) -procedere con la terza e così via fino ad ottenere solo le combinazioni possibili (Così diventa possibile anche risfruttare parzialmente le ricerche) Naturalmente le liste occupano più spazio del testo, ma meno di un json enorme.

Questa è una vostra scelta implementativa.
Strategica è la scelta di mantenere un summaries completo in memoria e filtrarlo all'occorrenza o richiederlo ogni volta al WS con gli opportuni filtri. Attualmente il WS del summaries è molto lento ma tra qualche settimana dovrebbe essere disponibile in test un WS molto più prestante.

> Naturalmente le liste occupano più spazio del testo, ma meno di un json enorme.

il summaries è generalmente molto piccolo, più grande è la risposta con i dati

> Questo sempre sottintendendo che sarebbe meglio utilizzare un api che non restituisce tutto ma solo quanto di interesse.

puoi specificare meglio il problema?
al summaries credo tu possa applicare tutti filtri necessari:
 https://rmap.cc/borinud/api/v1/dbajson/*/*/*/254,0,0/103,2000,-,-/B12101/summaries
 https://rmap.cc/borinud/api/v1/dbajson/-/1132879,4450075/urbane/254,0,0/103,2000,-,-/B12101/summaries

dovrebbero essere disponibili anche delle estensioni non documentate:
 https://test.rmap.cc/borinud/api/v1/dbajson/-/*/*/254,0,0/103,2000,-,-/B12101/summaries?latmin=4412345&latmax=4512345&lonmin=1012345&lonmax=1212345
 https://test.rmap.cc/borinud/api/v1/dbajson/-/*/*/254,0,0/103,2000,-,-/B12101/summaries?yearmin=2019&monthmin=3&daymin=10&hourmin=12&minumin=15&secmin=20&yearmax=2020&monthmax=6&daymax=20&hourmax=18&minumax=45&secmin=45

anche queste estensioni saranno disponibili nel server di test nelle prossime settimane

**Comment by fabiodepas** [comment]
> puoi specificare meglio il problema?
al summaries credo tu possa applicare tutti filtri necessari:

L'idea iniziale era quella di utilizzare le api, ma sono troppo lente adesso, credo dobbiamo che per provare  con questo metodo dobbiamo apsettare perchè qualsiasi chiamata la prima volta mi cosa 20 secondi e per dei filtri dinamici non penso sia l'ideale. Stiamo valuando eventuali  alternative.

**Comment by pat1** [comment]
tra breve dovrebbe essere disponibile una versione di borinud con summario più veloce da testare

**Comment by pat1** [comment]
abbiamo in test la nuova versione di borinud che dovrebbe dare prestazioni migliori.
https://test.rmap.cc
Evidenzio che attualmente in dbajson e jsonline il campo "vars" previsto come array in borind attualmente contiene un solo elemento, fatto non vincolante per il futuro. Se deve essere considerato un vincolo ne dobbiamo parlare.

**Comment by pat1** [comment]
mi pare la scelta sia stata fatta.
Per eventuali ottimizzazioni al summary prego aprire un'altra issue
