### ISSUE TITLE
Invalidazione manuale, e flag di qualità dei dati

### ISSUE THREAD

**Issue by gianpieropa** [ARPA-SIMC/cosudo#28]
Nel capitolato è indicato di far visualizzare su mappa gli attributi di confidenza generati dal controllo automatico, che dovrebbero essere i seguenti :B33192, B33193, B33194.
Sul db di test non sembrano presenti questi flag, il seguente script non restituisce nulla:
```
db = get_db()

for rec in db.query_data({"var": "B33194"}):
    print(rec)  
```
Come posso simulare le etichettature automatiche ? 
Mentre per l'invalidazione manuale quale è il flag che va inserito ?

**Comment by edigiacomo** [comment]
Puoi ispirarti a questo nostro script https://github.com/ARPA-SIMC/dba_qcfilter/blob/master/dba_qcfilter/cli.py

**Comment by edigiacomo** [comment]
> Mentre per l'invalidazione manuale quale è il flag che va inserito ?

B33196=1

**Comment by gianpieropa** [comment]
Sto provando ad inserire degli attributi nel db, ma dopo averli inseriti non risultano, sto sbagliando qualcosa? 
```
 with memdb.transaction() as tr:
        for rec in tr.query_data({"var": "B12101"}):
            rec.insert_attrs({"B33196": 1})
            print(rec["attrs"])
```
Risultato:
```
[]

```

**Comment by edigiacomo** [comment]
Leggendo la doc https://arpa-simc.github.io/dballe/python_how/attributes.html#updating-attributes direi che non stai sbagliando. Il comportamento ha anche un suo senso: l'oggetto `rec` è l'n-esimo risultato di una query all'interno di una transazione e probabilmente mantiene il suo stato in modo coerente con quanto presente in DB. L'esito di `rec.insert_attrs` è verificabile solo dopo la commit (fatta automaticamente alla fine del blocco `with`) tramite una nuova query al DB (che a quel punto ha il risultato).

**Comment by gianpieropa** [comment]
Perfetto, grazie mille! Un' altra domanda le api borinud restituiscono anche gli attributi? Da quanto ho notato non mi sembra. Allego la risposta ad una richiesta che dovrebbe contenere degli attributi per la var B12101,  in particolare dovrebbe contenere l'attributo B33196
```
{
   "ident":null,
   "lon":1057043,
   "lat":4430012,
   "network":"mnw",
   "date":"2020-07-14T00:00:00",
   "data":[
      {
         "vars":{
            "B12101":{
               "v":283.26
            }
         },
         "timerange":[
            254,
            0,
            0
         ],
         "level":[
            103,
            2000,
            null,
            null
         ]
      }
   ]
}
```

**Comment by edigiacomo** [comment]
A memoria e leggendo il codice di borinud https://github.com/r-map/rmap/blob/master/python/borinud/v1/views.py#L28 mi pare di no, chiedo a @pat1 conferma.

**Comment by gianpieropa** [comment]
Nel caso di conferma, come mi consigliate di procedere effettuiamo delle modifiche a borinud in modo tale che ci restituisca gli attributi ? Perché gli attributi mi sono necessari per la visualizzazione su mappa dei flag di qualità e delle invalidazioni

**Comment by pat1** [comment]
la mia ipotesi sarebbe: per geojson no e per gli altri formati si
Se non è così è un bug devo verificare e nel caso dobbiamo assolutamente e immediatamente integrarle (noi ARPAE) in borinud.

**Comment by pat1** [comment]
è un bug:
https://github.com/r-map/rmap/issues/319

**Comment by gianpieropa** [comment]
Attendo un fix allora, grazie

**Comment by pat1** [comment]
dovrebbe esser stato implementato:
https://test.rmap.cc/borinud/api/v1/dbajson/fgrazzini/1131908,4449301/fixed/254,0,0/103,2000,-,-/B13003/timeseries/2020/09/25/09?dsn=report_fixed&query=attr

servono forse ancora un po' di test.
I commit di rmap sono in git ma non ancora in copr.
Per il momento chiudo la issue, se necessario riaprite.

**Comment by pat1** [comment]
Evidenzio che per ottenere gli attributi la url di borinud deve contenere il parametro "&query=attr"
