### ISSUE TITLE
Stili grafici su diverse tipologie di feature 

### ISSUE THREAD

**Issue by fabiodepas** [ARPA-SIMC/cosudo#3]
Mediante flask, skinnywms e magics abbiamo realizzato un wms, abbiamo eseguito diversi test di visualizzazione con diversi grib, resta da  capire ora  in base alla tipologia di feature da mostrare quale specifico stile grafico applicare.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
