### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by gianpieropa** [ARPA-SIMC/cosudo#30]
Vorrei avere più informazioni sulla struttura del grib repository, in dettaglio vorrei sapere se ci verrà fornito un grib per ogni giorno (e per tipo di dato), o ci verrà fornito un grib per fascia oraria (come il seguente [repository](https://github.com/ARPA-SIMC/qc_sample_data/tree/master/radar/grib2))?

**Comment by pat1** [comment]
La domanda non mi è chiara.
Cosa intendi per "struttura del grib repository" ?
Provo comunque a dare una risposta:
I grib contengono (salvo una speciale possibilità che noi evitiamo accuratamente) un solo campo bidimensionale (grigliato)
I grib possono essere uno dietro l'altro dentro un file
I file si possono "giuntare" (append) uno dietro l'altro
I singoli grib possono essere letti singolarmente da un file

Per ottenere un file di grib dovete estrarre i dati dal nostro archivio arkimet
Cosa ci sarà nel file estratto dipende dalla query a arkimet che fate (e che vi suggeriremo) vedi #14

**Comment by fabiodepas** [comment]
Avevo capito che ad arkimet dobbiamo fare ad esempio  una query al giorno e salvare i file in un grib repository, 
questo repository mi  pareva  lo avessimo descritto come una semplice cartella con grib file dentro, 
naturalmente i grib possono contenere diversi dati, layer diversi ed istanti temporali diversi, 
dato che  le query arkimet non le abbiamo ancora volevamo capire se 
i grib conterranno singoli grigliati (singoli dati con  un solo istante  temporale, anche se mi pare di capire si  voglia evitare), 
tutti i grigliati dello stesso dato con annesse tutte le fasce di tempo
oppure tutti idati con tutti gli  istanti temporaliin  un unico file.
Non so se sono  stato chiaro.

**Comment by pat1** [comment]
> Avevo capito che ad arkimet dobbiamo fare ad esempio una query al giorno e salvare i file in un grib repository,

si può fare una o più query (non so se con una sola query si riesca a fare)

> questo repository mi pareva lo avessimo descritto come una semplice cartella con grib file dentro,

   si, con file con dentro dei grib

> naturalmente i grib possono contenere diversi dati, layer diversi ed istanti temporali diversi,

   un file contiene dei grib, un grib contiene unsolo grigliato con un solo layer, parametro e istante temporale ...

>dato che le query arkimet non le abbiamo ancora volevamo capire se
i grib conterranno singoli grigliati (singoli dati con un solo istante temporale, anche se mi pare di capire si voglia evitare),

   i file con dentro dei grib estratti da arkimet solitamente non contengono un singolo grib perchè altrimenti il numero delle query  
   sarebbe esagetato; le query si possono organizzare nel limite del possibile come fa più comodo

>tutti i grigliati dello stesso dato con annesse tutte le fasce di tempo
oppure tutti idati con tutti gli istanti temporaliin un unico file.

   direi che si può fare come preferite
   cerco di mandare un esempio di query in giornata se riesco

**Comment by pat1** [comment]
devo specificare che dei dati in formato grib da visualizzare:
https://github.com/ARPA-SIMC/qc_sample_data
radar e satellite dipendono da convertitori/software facenti parte della commessa che non mi risultano ancora utilizzabili.
Quindi per il momento è possibile estrarre da arkimet i dati relativi al modello
https://github.com/ARPA-SIMC/qc_sample_data
come vedete i dati sono di differenti tipologie:
* analisi
* previsioni

inoltre i formati sono due:
* grib versione1
* grib versione 2

**Comment by pat1** [comment]
Attivare utente per autenticazione su:
https://simc.arpae.it/arkiweb/
(Emanuele)

questa la query arkimet per analisi  dataset lama5:
```
query: reftime: >= 2020-10-01 00:00:00,<=2020-10-06 12:00:00; product:GRIB1,200,2,2 or GRIB1,200,2,11 or GRIB1,200,2,17 or GRIB1,200,2,33 or GRIB1,200,2,34 or GRIB1,200,2,51 or GRIB1,200,2,61 or GRIB1,200,2,71 or GRIB1,200,2,73 or GRIB1,200,2,74 or GRIB1,200,2,75 or GRIB1,200,2,111 or GRIB1,200,2,112; level:GRIB1,1 or GRIB1,102 or GRIB1,105,2 or GRIB1,105,10
```
e questa per previsioni dataset cosmo_2I:
```
query: reftime: =2020-10-06 12:00:00; product:GRIB1,80,2,2 or GRIB1,80,2,11 or GRIB1,80,2,33 or GRIB1,80,2,34 or GRIB1,80,2,51 or GRIB1,80,2,52 or GRIB1,80,2,61 or GRIB1,80,2,65 or GRIB1,80,2,71 or GRIB1,80,2,73 or GRIB1,80,2,74 or GRIB1,80,2,75 or GRIB1,80,201,22 or GRIB1,80,201,23; level:GRIB1,1 or GRIB1,102 or GRIB1,105,2 or GRIB1,105,10
```

Estrazione dei dati da arkiweb

Il servizio /services/arkiweb/data permette di estrarre i dati. I parametri GET a disposizione sono:

    datasets[]=DATASET: dataset da interrogare (può essere dato più volte)
    query=QUERY: query con sintassi Arkimet (vedi ArkimetQuery) per filtrare i dataset, se non specificato equivale a "tutto".
    postprocess=POSTPROCESSOR ARGS: postprocessatore (ed eventuali argomenti) da utilizzare (vedi ArkimetPostprocess). Il postprocessatore deve essere abilitato per i dataset selezionati. 

quindi esempio con curl che dovrà essere portato in python parametrizzato solo con reftime:

```
$curl -sgG --data-urlencode "datasets[]=lama5" --data-urlencode "query=reftime: >= 2020-10-01 00:00:00,<=2020-10-06 12:00:00; product:GRIB1,200,2,2 or GRIB1,200,2,11 or GRIB1,200,2,17 or GRIB1,200,2,33 or GRIB1,200,2,34 or GRIB1,200,2,51 or GRIB1,200,2,61 or GRIB1,200,2,71 or GRIB1,200,2,73 or GRIB1,200,2,74 or GRIB1,200,2,75 or GRIB1,200,2,111 or GRIB1,200,2,112; level:GRIB1,1 or GRIB1,102 or GRIB1,105,2 or GRIB1,105,10" https://USER:PASSWORD@simc.arpae.it/services/arkiweb/data --output ana.grib1
```

```
$curl -sgG --data-urlencode "datasets[]=cosmo_2I" --data-urlencode "reftime: =2020-10-06 12:00:00; product:GRIB1,80,2,2 or GRIB1,80,2,11 or GRIB1,80,2,33 or GRIB1,80,2,34 or GRIB1,80,2,51 or GRIB1,80,2,52 or GRIB1,80,2,61 or GRIB1,80,2,65 or GRIB1,80,2,71 or GRIB1,80,2,73 or GRIB1,80,2,74 or GRIB1,80,2,75 or GRIB1,80,201,22 or GRIB1,80,201,23; level:GRIB1,1 or GRIB1,102 or GRIB1,105,2 or GRIB1,105,10" https://USER:PASSWORD@simc.arpae.it/services/arkiweb/data --output fore.grib1
```

**Comment by edigiacomo** [comment]
> Attivare utente per autenticazione su:
> https://simc.arpae.it/arkiweb/
> (Emanuele)

@pat1 A quali dataset devono accedere? Solo `lama5` e `cosmo_2I`?

@brancomat ti chiedo una mano per creare utente e gruppo opportunamente.

**Comment by pat1** [comment]
> A quali dataset devono accedere? Solo lama5 e cosmo_2I?
per ora si

**Comment by brancomat** [comment]
Utente creato, comunico credenziali con altri canali a @pat1

**Comment by gianpieropa** [comment]
Ho provato ad effettuare la seguente query attraverso richiesta http (con i parametri codificati ovviamente) ma restituisce un file vuoto, sto sbagliando qualcosa?
`datasets[]=lama5&query=reftime: >= 2020-10-08 00:00:00,<=2020-10-12 00:00:00; product:GRIB1,200,2,2 or GRIB1,200,2,11 or GRIB1,200,2,33 or GRIB1,200,2,51 or GRIB1,200,2,61 or GRIB1,200,2,71 or GRIB1,200,2,73 or GRIB1,200,2,74 or GRIB1,200,2,75 or GRIB1,200,2,111 or GRIB1,200,2,112; level:GRIB1,1 or GRIB1,102 or GRIB1,105,2 or GRIB1,105,10`
Ho provato ad utilizzare anche queste query ma con lo stesso risultato (anche tramite curl)

> 
> quindi esempio con curl che dovrà essere portato in python parametrizzato solo con reftime:
> 
> ```
> $curl -sgG --data-urlencode "datasets[]=lama5" --data-urlencode "query=reftime: >= 2020-10-01 00:00:00,<=2020-10-06 12:00:00; product:GRIB1,200,2,2 or GRIB1,200,2,11 or GRIB1,200,2,17 or GRIB1,200,2,33 or GRIB1,200,2,34 or GRIB1,200,2,51 or GRIB1,200,2,61 or GRIB1,200,2,71 or GRIB1,200,2,73 or GRIB1,200,2,74 or GRIB1,200,2,75 or GRIB1,200,2,111 or GRIB1,200,2,112; level:GRIB1,1 or GRIB1,102 or GRIB1,105,2 or GRIB1,105,10" https://USER:PASSWORD@simc.arpae.it/services/arkiweb/data --output ana.grib1
> ```
> 
> ```
> $curl -sgG --data-urlencode "datasets[]=cosmo_2I" --data-urlencode "reftime: =2020-10-06 12:00:00; product:GRIB1,80,2,2 or GRIB1,80,2,11 or GRIB1,80,2,33 or GRIB1,80,2,34 or GRIB1,80,2,51 or GRIB1,80,2,52 or GRIB1,80,2,61 or GRIB1,80,2,65 or GRIB1,80,2,71 or GRIB1,80,2,73 or GRIB1,80,2,74 or GRIB1,80,2,75 or GRIB1,80,201,22 or GRIB1,80,201,23; level:GRIB1,1 or GRIB1,102 or GRIB1,105,2 or GRIB1,105,10" https://USER:PASSWORD@simc.arpae.it/services/arkiweb/data --output fore.grib1
> ```

**Comment by edigiacomo** [comment]
Provate adesso.

(@brancomat: il file di configurazione di arkiweb non era stato aggiornato)

**Comment by gianpieropa** [comment]
Nulla provato di nuovo anche con curl e con le query postate da voi, la seconda query mi ha restituito il seguente risultato 
![Schermata del 2020-10-13 09-56-49](https://user-images.githubusercontent.com/68102511/95832484-98567800-0d3a-11eb-966a-8030b04054b8.png)

**Comment by gianpieropa** [comment]
Perfetto ora sembra funzionare da curl, lascio l'issue aperta nel caso abbia bisogno di altri chiarimenti. Grazie
