### ISSUE TITLE
Visualizzazione dati su mappa

### ISSUE THREAD

**Issue by gianpieropa** [ARPA-SIMC/cosudo#31]
Per la visualizzazione dei dati di borinud su mappa abbiamo optato (come da capitolato) per i cluster con la rappresentazione dei dati (per esempio temperatura) 
![Schermata del 2020-09-24 11-20-50](https://user-images.githubusercontent.com/68102511/94126561-0c96ad80-fe58-11ea-8c36-83bff4b45ff0.png)

Mentre per quanto riguarda il vento è indicato di rappresentarli con la rosa dei venti, si intende una cosa del genere?
![wind](https://user-images.githubusercontent.com/68102511/94126743-4798e100-fe58-11ea-80d9-c14540346472.gif)

**Comment by pat1** [comment]
no, la rappresentazione del vento che portate come esempio è fattibile solo su grigliato e rappresenta le streamline (linee di flusso)
Le rose dei venti sono cose diverse:
https://en.wikipedia.org/wiki/Wind_rose
un esempio lo trovate a questa pagina cercando rosa dei venti :
https://www.meteoblue.com/it/tempo/historyclimate/climatemodelled/borgosesia_italia_3181749

Non ho fatto una garnde ricerca ma una possibilità è questa:
http://windhistory.com/about.html
http://windhistory.com/station.html?KJWG
http://windhistory.com/map.html#7.00/35.482/-98.121

tempo fa avevamo iniziato a lavorare su una presentazione grafica simile a questa:
http://yr.hveem.no/
e alcuni software li abbiamo raccolti qua:
https://github.com/r-map/rmap/tree/master/python/amatyr/static/amatyr/js
vi potrebbe servire nello specifico:
https://github.com/r-map/rmap/blob/master/python/amatyr/static/amatyr/js/windrose.js
