### ISSUE TITLE
Aggiunta ad rmap

### ISSUE THREAD

**Issue by gianpieropa** [ARPA-SIMC/cosudo#34]
Per l'aggiunta ad rmap dopo aver eseguito l'installazione del rpm, bisogna modificare i file di settings e di url, in quanto non credo si possa automatizzare tale operazione, giusto?
In caso di conferma procedo alla pubblicazione della nuova versione su copr

**Comment by pat1** [comment]
https://docs.djangoproject.com/en/3.1/intro/reusable-apps/

in estrema sintesi in rmap project dovremo fare:

1. Add "polls" to your INSTALLED_APPS setting like this::

    INSTALLED_APPS = [
        ...
        'polls',
    ]

2. Include the polls URLconf in your project urls.py like this::

    path('polls/', include('polls.urls')),

3. Se necessario Run ``python manage.py migrate`` to create the polls models.
