### ISSUE TITLE
Pubblicazione su copr

### ISSUE THREAD

**Issue by gianpieropa** [ARPA-SIMC/cosudo#37]
Ho proceduto a pubblicare il pacchetto rpm su copr, ma ho riscontrato un problema che non mi si era presentato prima. Praticamente la creazione del rpm fallisce per fedora (qui il [log](https://download.copr.fedorainfracloud.org/results/simc/cosudo/fedora-32-x86_64/01709021-django-dynamic-map-borinud/builder-live.log.gz) ), mentre per centos funziona perfettamente. Avete idee sul perché? ho provato a fare un pò di ricerche (dato che ho meno esperienza con fedora rispetto ad ubuntu) ma non sono riuscito a venirne a capo.

**Comment by pat1** [comment]
direi che il problema deriva dall'intenzione del build di fare il pacchetto di debug, cosa inusuale per pacchetti python.
Forse dipende dal contenuto.
Per forzare la cosa mi parerrebbe più corretto utilizzare
%global debug_package %{nil}
invece di:
%define __debug_package %{nil}

Segnalo che la licenza utilizzata non è corretta:
License: BSD 3-Clause

**Comment by gianpieropa** [comment]
Nulla continua a fallire su fedora, la cosa strana è che inizialmente funzionava e non sono state apportate modifiche al file spec, questo è il nuovo [file di log](https://download.copr.fedorainfracloud.org/results/simc/cosudo/fedora-32-x86_64/01711464-django-dynamic-map-borinud/builder-live.log.gz)

**Comment by pat1** [comment]
potrebbe essere un errore "casuale"; io in questo caso proverei un "ritenta sarai più fortunato"
