### ISSUE TITLE
Attributi borinud

### ISSUE THREAD

**Issue by gianpieropa** [ARPA-SIMC/cosudo#38]
Provando a caricare gli attributi per dei test, ho notato che una volta caricati borinud comunque non li restituiva, invece facendo una query da python gli attributi erano presenti. Guardando nel codice di borinud, credo di aver individuato il problema.
Nella classe DballeDB di borinud la funzione fill_data_db è la seguente:
```
   def fill_data_db(self, rec, memdb):

        db = self.__open_db()

        with db.transaction() as tr:
            with memdb.transaction() as memtr:
                for cur in tr.query_data(rec):
                    memtr.insert_data(cur.data, True, True)
```
Mentre credo debba essere modificata in questo mod:
```
    def fill_data_db(self, rec, memdb):

        db = self.__open_db()
        #aggiunta
        if (self.attr):
            rec["query"] = "attrs"
        with db.transaction() as tr:
            with memdb.transaction() as memtr:
                for cur in tr.query_data(rec):
                    memtr.insert_data(cur.data, True, True)
```
Non so se è esatto ma così facendo borinud restituisce gli attributi correttamente

**Comment by pat1** [comment]
risolto con 
https://github.com/r-map/rmap/commit/dbcae2f1f5cf9617336865d178e8b1c9fc52c34d
grazie della segnalazione.
Ma credo che il tuo problema non derivi da questo che comportava problemi solo facendo un merge di differenti "sorgenti" e non si evidenzia se estrai dati degli ultimi 7 giorni.

Ho cercato di evidenziare che per ottenere gli attributi dalle web api borinud bisogna aggiungere &query=attr per una questione di ottimizzazione, ma forse non è troppo chiaro...

> Evidenzio che per ottenere gli attributi la url di borinud deve contenere il parametro "&query=attr"
_Originally posted by @pat1 in https://github.com/ARPA-SIMC/cosudo/issues/28#issuecomment-698877794_

**Comment by gianpieropa** [comment]
> Ho cercato di evidenziare che per ottenere gli attributi dalle web api borinud bisogna aggiungere &query=attr per una questione di ottimizzazione, ma forse non è troppo chiaro...


Sisi era chiaro e infatti lo avevo inserito, probabilmente è perché sto utilizzando un db con dati di luglio (?)

**Comment by pat1** [comment]
direi di si, dipende dalle configurazioni 
in setting.py ci sono le variabili BORINUD e BORINUDLAST che definiscono da quali sogenti prendere i dati: la prima per l'intero periodo in DB, BORINUDLAST per i dati dell'ultima settimana.
Usando dati antecedenti l'ultima settimana impica usare BORINUD e le cose rallentano un po'
