### ISSUE TITLE
Attributi cluster

### ISSUE THREAD

**Issue by gianpieropa** [ARPA-SIMC/cosudo#39]
Per la visualizzazione sommaria dei flag di qualità sui cluster ho pensato che per le invalidazioni posso mostrare il numero di dati invalidati sul numero dei totali (es. 25 of 300), mentre per gli altri flag di qualità è importante visualizzare il minimo o il massimo dei valori, oppure una media ?

**Comment by pat1** [comment]
se stai parlando delle spatialseries credo potrebbe bastare evidenziare ( magari facendo lampeggiare il backgriound) se almeno uno dei dati nel cluster è stato invalidato / nessun dato invalidato.
Però per fare una cosa semplice e flessibile come discusso all'ultimo incontro tutta la visualizzazione degli attributi potrebbe essere realizzata tramite dei filtri sulla visualizzazione dei dati:
* visualizza dati non invalidati e dati invalidati
* visualizza dati non invalidati
* visualizza dati invalidati

per i tre tipi di confidenza:
* visualizza dati con qualsiasi confidenza
* visualizza dati sotto la soglia X di confidenza
* visualizza dati sopra la soglia X di confidenza

i valori degli attributi potrebbe ro essere mostrati nel pop up relativo ai dati.
