### ISSUE TITLE
Integrazione continua

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/cosudo#4]
Integrazione continua
Lo sviluppo del software dovrà essere corredato da unit tests.
Quando sia possibile ogni issue aperta su github dovrà essere accompagnata da test automatici.
Ad ogni commit dovranno essere eseguiti, sulla piattaforma che ospita il codice, i test automatici.
Se i test automatici passano, il file spec del pacchetto dovrà essere inviato a Copr per la
pacchettizzazione automatica dell'ultima release.
I test dovranno essere verificati per:
● Python: 3.6
● Django: 2.2, 3.0
● Database: postgres, sqlite
● Distribuzioni: centos8, fedora 30 e successive versioni rilasciate fino alla consegna
Sarà possibile utilizzare la piattaforma Travis e le configurazioni già utilizzate da ARPAE-SIMC

**Comment by gianpieropa** [comment]
Ho richiesto l'abilitazione di travis per il repository cosudo, attendo che la accettiate.

**Comment by edigiacomo** [comment]
Abilitato

**Comment by gianpieropa** [comment]
Per quanto riguarda la pubblicazione su copr, devo utilizzare il seguente [repository](https://copr.fedorainfracloud.org/coprs/simc/stable/ )? E nel caso dove posso reperire il file di configurazione da utilizzare con copr-cli?

**Comment by edigiacomo** [comment]
Il token possiamo aggiungerlo noi, chiedo però a @pat1 in quale repository Copr pensava di mettere il pacchetto. Proposte:
* https://copr.fedorainfracloud.org/coprs/pat1/rmap/
* https://copr.fedorainfracloud.org/coprs/simc/stable: eviterei finché siamo in fase di sviluppo, ma direi assolutamente no se `cosudo` dipende da pacchetti in `pat1/rmap` (dipendenza ciclica: `pat1/rmap` dipende da `simc/stable`).
* https://copr.fedorainfracloud.org/coprs/simc/test: qui possiamo fare quello che ci pare
* Altro, e.g. https://copr.fedorainfracloud.org/coprs/simc/cosudo

**Comment by pat1** [comment]
Una soluzione potrebbe essere di fare un repo dedicato che chiede pat1/rmap.
Non ci vedo controindicazioni.
Se ce ne sono allora visto che credo che cosudo dipenda da pacchetti in rmap  per il momento propongo:
https://copr.fedorainfracloud.org/coprs/pat1/rmap/

**Comment by pat1** [comment]
L'unica configurazione richiesta nel caso di un repo dedicato credo sia la seguente:
External Repository List
The following repositories are accessible during builds
    copr://simc/stable
    copr://pat1/rmap

**Comment by edigiacomo** [comment]
Creato https://copr.fedorainfracloud.org/coprs/simc/cosudo/ e aggiunto il token, che viene usato da `copr-cli`.

Di seguito un esempio  (sostituire `SPECFILE` con il path relativo del file spec che sarà presente nel repository):

```
deploy:
    skip_cleanup: true
    provider: script
    script: docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ fedora:latest /bin/sh -c "dnf install -y copr-cli && copr-cli --config .copr build --nowait simc/cosudo SPECFILE"
```

**Comment by edigiacomo** [comment]
Dimenticavo: le suddette aggiunte sono state fatte nella commit 05933ef

**Comment by gianpieropa** [comment]
Prima del deploy la build di travis fallisce (credo nel recuperare le variabili per decriptare il file), nel seguente punto:
`openssl aes-256-cbc -K $encrypted_6d2e60986cdb_key -iv $encrypted_6d2e60986cdb_iv -in .copr.enc -out .copr -d`

Questa è la [build](https://travis-ci.com/github/ARPA-SIMC/cosudo/jobs/383096613) dove fallisce, avete idee?

**Comment by gianpieropa** [comment]
La [build](https://travis-ci.com/github/ARPA-SIMC/cosudo/jobs/383105072) su travis fallisce al seguente comando :
`openssl aes-256-cbc -K $encrypted_6d2e60986cdb_key -iv $encrypted_6d2e60986cdb_iv -in .copr.enc -out .copr -d`
con il seguente risultato:
`iv undefined`
Credo non riesca ad accedere alle variabili, avete idee?

**Comment by edigiacomo** [comment]
Ho guardato le impostazioni su Travis e le variabili sono presenti. Anche da CLI mi risultano

```
 $ travis env list
# environment variables for ARPA-SIMC/cosudo
encrypted_6d2e60986cdb_key=[secure]
encrypted_6d2e60986cdb_iv=[secure]
```

**Comment by edigiacomo** [comment]
Ho provato a cifrare nuovamente il file, vediamo se si ripiglia.

**Comment by edigiacomo** [comment]
Ho capito la causa del comportamento misterioso: cosudo è attivato sia su travis-ci.com che su travis-ci.org. In quest'ultimo abbiamo tutti i nostri progetti, compreso cosudo, e funziona tutto regolarmente (si veda https://travis-ci.org/github/ARPA-SIMC/cosudo). Su travis-ci.org invece no.

Non abbiamo mai fatto la migrazione dei nostri progetti da org a com e non vorrei creare problemi ai build di tutti i progetti facendolo ora, quindi per ora vi chiedo di ignorare gli errori nei build da travis-ci.com mentre pianifichiamo il passaggio da org a com (pingo @brancomat).

**Comment by gianpieropa** [comment]
Perfetto, grazie mille

**Comment by edigiacomo** [comment]
Aggiornamento: ho disabilitato il build su travis-ci.com e ho lasciato quello su travis-ci.org, quindi adesso non dovreste più ricevere notifiche dal primo.

**Comment by fabiodepas** [comment]
La release da pubblicare su Copr come viene passata una volta terminato il test con Travis?  Perchè mi sembra che su Copr finsca un archivio che viene posto su Git

**Comment by edigiacomo** [comment]
Il campo [`Source0`][1] nello spec file deve contenere l'URL a cui è possibile scaricare il sorgente: consiglio l'URL della release su GitHub di un tag corrispondente alla versione pacchettizzata (puoi ispirarti a https://github.com/ARPA-SIMC/arkimet/blob/master/fedora/SPECS/arkimet.spec)

Copr, una volta inviato lo spec, si occupa di scaricare il sorgente da `Source0`, pacchettizzarlo e pubblicarlo.

[1]: https://github.com/ARPA-SIMC/cosudo/blob/master/django-dynamic-map-borinud/django-dynamic-map-borinud.spec#L10+
