### ISSUE TITLE
nodata after a var selection on dynamic map

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/cosudo#41]
https://test.rmap.cc/dynamic/map/

seleziona la variabile PRESSURE
SEARCH
la risposta è 
nessun risultato

questo non dovrebbe essere possibile visto che il summary dovrebbe presentare solo dati realmente presenti: almeno un dato deve esserci altrimenti non deve esserci quella varibile nel summary ...

**Comment by gianpieropa** [comment]
Forse è relativo ad un bug già risolto, provate aspettando che il box con la data venga riempito dalla data corrente.
Procederò a rilasciare una nuova release con le nuove features entro domani
