### ISSUE TITLE
Tabelle vm2 

### ISSUE THREAD

**Issue by gianpieropa** [ARPA-SIMC/cosudo#43]
Rimaniamo  in attesa come deciso in riunione delle api per le tabelle vm2 di conversione e quelle che forniscono le stazioni, livelli, timerange, network e variabili non presenti nel db, necessari per l'ultimazione della parte di invalidazione.

**Comment by edigiacomo** [comment]
Ciao, l'idea è quella di fornire un URL a cui scaricare il file in formato JSON (oppure in Lua, che poi può essere facilmente convertito). Per ora, potete usare il file dal repository di `meteo-vm2`. Di seguito, il codice per scaricare il file e convertirlo in JSON su stdout.

Prima, installate i pacchetti necessari `dnf install lua-http lua-json` (disponibili sia per fedora >=32 che per centos8).

Poi, potete usare questo script:

```lua
json = require "json"
http_request = require "http.request"
url = "https://raw.githubusercontent.com/ARPA-SIMC/meteo-vm2/master/conf/bufr.lua"
headers, stream = assert(http_request.new_from_uri(url):go())
body = assert(stream:get_body_as_string())
print(json.encode(body))
```

In seguito, basterà solo cambiare l'URL (oppure convertire lo script in uno che scarica solo il JSON).
