### ISSUE TITLE
Come posso testare il lavoro fatto finora?

### ISSUE THREAD

**Issue by PasqualiSIMC** [ARPA-SIMC/cosudo#44]
E' possibile testare il lavoro fatto finora? In particolare mi riferisco alla visualizzazione delle invalidazioni. Inoltre è possibile testarlo su un set di dati recente (ultimi giorni, la rete RMAP, temperatura e precipitazioni) ?

**Comment by gianpieropa** [comment]
Abbiamo messo su un [server di test,](http://18.196.3.89:8888/dynamic/map/) provvederemo ad aggiornare il server man mano che terminiamo i task.
