### ISSUE TITLE
DEM in formato ESRI FLT

### ISSUE THREAD

**Issue by fabiodepas** [ARPA-SIMC/cosudo#47]
Salve, dove posso trovare qualche vostro file DEM in formato ESRI FLT così da poterli testare?

**Comment by pat1** [comment]
da assegnare a 
PasqualiSIMC
ma non fa parte del gruppo ...

**Comment by dcesari** [comment]
Io ho dei dem in formato analogo ma con valori interi, se servono.

**Comment by fabiodepas** [comment]
Se sono  quelli  che verranno dati in pasto al wms vanno  bene.

**Comment by dcesari** [comment]
Non credo, sono parte di una mia "collezione privata", aspetto notizie da @pat1.
Aggiungo incidentalmente, forse lo sapete, che i DEM di quel tipo di possono fondere in un unico virtual dataset gdal con `gdalbuildvrt`.

**Comment by pat1** [comment]
Pasquali entro domani fornirà il DEM
quando accetterà l'invito al team potrò assegnargli la issue

comunque @dcesari puoi fornire i tuoi DEM da "collezione privata" così ci facciamo dei test

**Comment by dcesari** [comment]
Ho caricato su Gdrive un tar derivato da dati estratti da http://viewfinderpanoramas.org/dem3.html a 3" d'arco (~100m) e rielaborati da me per creare i relativi file descrittori ESRI bil/hdr, swappare i dati (script `conv.sh`) e creare il dataset virtual gdal associato.

https://drive.google.com/file/d/1LA-njY5vMDe0xELJJ_Bk3uavWBsAMR2B/view?usp=sharing

**Comment by PasqualiSIMC** [comment]
Ho caricato su Gdrive (https://drive.google.com/drive/folders/17hUQYKxwJZH5zk50spDmIiuLB672uRSz?usp=sharing) il dem che verrà caricato su WMS
