### ISSUE TITLE
[Conversione netcdf2grib] parametro timeRangeIndicator

### ISSUE THREAD

**Issue by fabiodepas** [ARPA-SIMC/cosudo#49]
Come potete vedere nell'immagine ho trovato questo parametro timeRangeIndicator, nell'esploarazione (fatta nei giorni scorsi) dei tool di conversione in fortran, avevo trovato  che nel  caso di GRIB1 il valore da impostare fosse 4, nel vostro file trovo impostato 13, non so se sia un problema di tavole di conversione dovuto al sistema, cosa facciamo, impotiamo13? 
nell'mmagine sotto potete ossevare a sinistra un file generato da  noi, a destra uno degli esempi creati da voi, il file netcdf da cui sono stati generati i GRIB dovrebbe essere il medesimo.
![Schermata da 2020-11-12 11-52-48](https://user-images.githubusercontent.com/68106378/98931591-82290c80-24de-11eb-8313-a5780b2e3795.png)

**Comment by fabiodepas** [comment]
Per i restanti attributi, a parte il "centre" che nei vostri file risulta 80 e nel nostro 200, i grib1 e 2 generati sembrano essere identici a  quelli dei vostri esempi.

**Comment by pat1** [comment]
mi raccomando il tool non si chiama netcdf2grib ma radarnetcdf2grib.
riassegno a Pierpaolo per quanto riguarda il radar e Davide per decidere lo standard di scrittura ...

**Comment by palberoni** [comment]
Abbiamo fatto la scelta di impostare il timerangeindicator a 13 perchè abbiamo a che fare con cumulate osservate (nel caso radar). 
Il valore 4 fà riferimento ad output di modelli previsionali con cumulate "previste".

Quindi manteniamo il 13.

**Comment by fabiodepas** [comment]
Perfetto, grazie mille.
