### ISSUE TITLE
cosudo dovrebbe essere una app django indipendente

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/cosudo#5]
Ho visto che è stato effettuato un fork di tutto il progetto rmap che comprende firmware per microcontrollori etc.
Forse non specificata nel capitolato perchè sottointesa e a noi evidente, lo sviluppo era richiesto per una APP django eventualmente da integrare in rmap o in altri web server.
E' possibile che l'app cosudo richieda alcune app del pacchetto RMAP per sfruttare se necessario alcune funzionalità fornite da queste app (quali alcune tabelle di showdata), ma la cosa è del tutto opzionale.
L'app showdata di rmap dovrà rimanere così come è magari decidendo se integrare alcune funzionalità di cosudo.
La distribuzione di cosudo dovrebbe essere una cosa di questo genere:
https://realpython.com/installable-django-app/

e a titolo di esempio dovrebbe presentarsi similmente a:
https://github.com/mozilla/django-csp/

Ossia una app da integrare in un progetto e il nome della app non dovrà essere showdata (suggerisco cosudo).

Suggerisco anche di utilizzare un directory del repository cosudo in quanto dovranno essere sviluppate altre componenti oltre alla app django

L'unica interazione necessaria tra cosudo e rmap sono i web service forniti dall'app borinud contenuta in rmap.

**Comment by fabiodepas** [comment]
Ristrutturiamo il progetto così da isolare le modifche in una nuova app.In  realtà abbiaamo clonato rmap poichè volevamo dedicare  una carlella al wms in flask.

**Comment by pat1** [comment]
mi pare sia stato realizzato
