### ISSUE TITLE
Travis test fallisce con fedora 30

### ISSUE THREAD

**Issue by gianpieropa** [ARPA-SIMC/cosudo#51]
Ho creato una una pull request (#50) con le nuove modifiche, ma fallisce per fedora 30. Perché non riesce ad abilitare il repository copr simc/stable necessario per la dipendenza a dballe. Avete suggerimenti ?

**Comment by gianpieropa** [comment]
Per il momento ho disattivato i test per fedora 30

**Comment by edigiacomo** [comment]
Per me puoi lasciarli disattivati: Fedora 30 ha raggiunto EOL a fine maggio (https://fedoraproject.org/wiki/End_of_life).
