### ISSUE TITLE
Tabelle vm2 (variabili)

### ISSUE THREAD

**Issue by gianpieropa** [ARPA-SIMC/cosudo#52]
Ho trasformato il file lua estrapolando le variabili e ho notato che hanno il seguente formato (con ripetute le variabili per ogni time-range o livello diverso):
`{"bcode": "B13011", "tr": 1, "p1": 0, "p2": 43200, "lt1": 1, "l1": "nil", "lt2": "nil", "l2": "nil", "unit": "mm"}`
Per come è strutturato la piattaforma di invalidazione invece, avrei bisogno di time-range e livelli scorporati, in modo tale da permettere la combinazione all'utente. Potrei effettuare l'estrapolazione a runtime ma aggiungerebbe un ulteriore calcolo abbastanza oneroso. Come procedo ?

**Comment by pat1** [comment]
@edigiacomo potremmo passare ad offrire un servizio del tipo borinud summaries ?
https://test.rmap.cc/borinud/api/v1/dbajson/*/*/*/*/*/*/summaries
per ora Be20 potrebbe utilizzare il servizio "fittizio" fornito da borinud per passare poi a un servizio fornito a partire da VM2 ?

**Comment by gianpieropa** [comment]
Sisi nessun problema, per le stazioni invece abbiamo usato il file lua senza nessun problema

**Comment by edigiacomo** [comment]
Premessa: sulla trasformazione da lua a json proposto in #43, ho trovato l'inghippo, mancava la trasformazione in Lua table prima del decode:

```
json = require "json"
http_request = require "http.request"
url = "https://raw.githubusercontent.com/ARPA-SIMC/meteo-vm2/master/conf/bufr.lua"
headers, stream = assert(http_request.new_from_uri(url):go())
body = assert(stream:get_body_as_string())
table = loadstring(body)()
print(json.encode(table))
```

Genero il file JSON

```
lua script.lua > source.json
```

Dopo questa premessa: forse non ho capito cosa intendi per "scorporare" livelli e timerange. Posso solo sospettare che tu voglia avere una lista dei timerange univoci ed una lista dei livelli univoci, in modo da fare due `<select multiple>` (o qualcosa del genere) nel menu di selezione (e a quel punto immagino pure una lista dei bcode). Ti chiedo conferma dell'interpretazione.

**Comment by gianpieropa** [comment]
Esatto è proprio quello che intendo

**Comment by edigiacomo** [comment]
In tal caso, ottenere gli insiemi univoci a partire dall'elenco delle variabili (che sono 528) non mi pare molto oneroso: ad esempio, il benchmark in Python per la creazione del set di timerange:

```
%timeit set((v["tr"], v["p1"], v["p2"]) for v in source["variables"].values())                                 
214 µs ± 19.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

E mi aspetto valori sempre nell'ordine di millisecondi in JavaScript.

Quando l'utente aggiorna una delle `<select>`, immagino che l'interfaccia debba scandire l'elenco delle variabili per controllare quelle che fanno match: questo vuol dire, senza ottimizzazione e nel caso peggiore, iterare una lista di 528 elementi, che è mi pare trascurabile.

Il servizio proposto da Paolo non risolverebbe il problema, perché avrebbe comunque le varie terne bcode, livello, trange ripetute. con l'aggravante del ritardo di un servizio runtime che deve fare dei conti (cioè quello di borinud).

**Comment by gianpieropa** [comment]
Allora procederò con l'estrapolazione a run-time
