### ISSUE TITLE
Database Gestione allarmi

### ISSUE THREAD

**Issue by fabiodepas** [ARPA-SIMC/cosudo#57]
Nel capitolato ci scrivete:
---------------------------
**Gestione allarmi**
Per lo sviluppo di questa sezione della web app dovrà essere utilizzato il framework
GeoDjango https://docs.djangoproject.com/en/3.0/ref/contrib/gis/
---------------------------

Nella prima riunione, rileggendo gli appunti presi, ci avete chiesto di non utilizzare PostGis. 
Dato che GeoDjango necessita di un DB Geospaziale, ci chiedevamo se per il salvataggio degli allarmi,  dobbiamo tener conto di quanto dettoci nella prima riunione o seguire il capitolato.Incascontrario  possiamo tranquillamente continuare a gestire le coordinate mediante semplici numeri e non con le utils di GeoDjango.

**Comment by pat1** [comment]
la risposta sintetica potrebbe essere così:
Se geodjango risulta MOLTO utile allora si può utilizzare.
Altrimenti se ne può fare volentieri senza.

Aggiungo che al momento sono utilizzati in RMAP in sostituzione di geodjango e quindi consigliati:
python-django-geojson
python-django-jsonfield
python-django-leaflet

in particolare:
django-geojson is a set of tools to manipulate GeoJSON with Django :
* (De)Serializer for (Geo)Django objects, querysets and lists
* Base views to serve GeoJSON map layers from models
* GeoJSON model and form fields to avoid spatial database backends
  (compatible with *django-leaflet* for map widgets)

**Comment by fabiodepas** [comment]
Grazie, procediamo senza anche perchè in questo caso non darebbe davvero un valore aggiunto, al più utilizziamo i pachetti consigliati.
