### ISSUE TITLE
cors

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/cosudo#58]
Segnalo che in RMAP si fa uso di:
python3-django-cors-headers

A Django App that adds Cross-Origin Resource Sharing (CORS) headers to
responses. This allows in-browser requests to your Django application from
other origins.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
