### ISSUE TITLE
Richiesta summary creazione allarmi

### ISSUE THREAD

**Issue by gianpieropa** [ARPA-SIMC/cosudo#59]
Per la creazione degli allarmi devo effettuare una richiesta a borinud con due periodi differenti, uno storico e uno che vogliamo analizzare, come posso richiedere queste due summary a borinud; perché effettuando le seguenti richieste ovvero con anno e mese differente il risultato è uguale:
https://rmap.cc/borinud/api/v1/dbajson/*/*/*/254,0,0/103,2000,-,-/B12101/summaries/2019/11/26
https://rmap.cc/borinud/api/v1/dbajson/*/*/*/254,0,0/103,2000,-,-/B12101/summaries/2020/11/26

**Comment by gianpieropa** [comment]
aggiungo che ho provato anche senza il giorno nella richiesta

**Comment by pat1** [comment]
bisogna interrogare due servizi borinud differenti:
quello storico per il momento può essere test.rmap.cc o rmap.cc
quello di analisi è quello locale con un solo periodo (qualche giorno) presente nel DB

in futuro potrebbe essere gestito differentemente, ma in ogni caso si tratta di specificare due URL differenti

spero questo sia fattibile senza problemi ...

**Comment by gianpieropa** [comment]
Quindi non vanno utilizzate date nella richiesta?

**Comment by pat1** [comment]
purtroppo al momento abbiamo un bug e il summaries non le considera, di conseguenza no.
dobbiamo correggere il bug e fare dei test e poi installare ... tempi troppo stretti.
Per ora devi simulare la cosa:
1) gestire le date (selezione del periodo attenzionato)
2) comporre le url
3) ignorare le url composte e usare due url statiche come da post sopra

per la selezione del periodo attenzionato puoi usare le estensioni alle web api borinud 
con i seguenti parametri della get con una url:

per summaries e timeseries
"yearmin"
"yearmax"
"monthmin"
"monthmax"
"daymin"
"daymax"
"hourmin"
"hourmax"
"minumin"
"minumax"
"secmin"
"secmax"

per summaries e spatialseries
"latmin"
"latmax"
"lonmin"
"lonmax"

non ho altre soluzioni da proporre in poche ore
vista la fretta puoi temporaneamente posticipare la realizzazione di 1)  e 2 )

**Comment by pat1** [comment]
dipende da
https://github.com/ARPA-SIMC/dballe/issues/240

**Comment by pat1** [comment]
non dipende da dballe ma da rmap:
https://github.com/r-map/rmap/issues/323

**Comment by pat1** [comment]
dovrei aver temporaneamente risolto disattivando la cache sui summaries.
Il parametro nel file di config è:

SUMMARYCACHE =  False

Ora però come conseguenza pare si sia rotto il menù dell'app in generale ...

**Comment by fabiodepas** [comment]
Di che menù si parla?

**Comment by pat1** [comment]
la release 11.0 di rmap dovrebbe aver risolto il problema; è installata su test.rmap.cc
il menu era quello di cosudo, ma come non detto; mi pare però che il summary all'avvio di cosudo dovrebbe a questo punto essere composto con la data corrente se non lo è già

**Comment by gianpieropa** [comment]
Ho corretto la richiesta delle summaries ora al caricamento la effettua con la data corrente (anno/mese)

**Comment by pat1** [comment]
alla fine dipende da:
https://github.com/ARPA-SIMC/dballe/issues/242

breve documentazione del summary:

Looking at the code, datetime extremes are taken into account when querying summaries, both xapian-based and in-memory ones.
However, summaries are summaries and not detailed data, and are aggregated by time interval. Querying by datetime bounds will return all summaries that intersect the query bounds.
For example, if you have a variable that's measured for a given station, report, level, and timerange, over the course of 5 years, and you query that variable with datetime bounds of one hour in that 5 years interval, you get the whole 5 years in the result set.
What the summary is telling you, is "the datetime bounds in your query are within the interval in which we have measurements for that variable".
Note that it doesn't necessarily mean that there are going to be data in that interval: if a variable is measured every monday, but you query_summary about it on a tuesday, you still get a result if that variable has been measured before and after that tuesday.

**Comment by gianpieropa** [comment]
Continuo ad avere problemi con le summary, sto utilizzando la versione di rmap su git, ma le summary con data continuano a non funzionare http://18.195.7.150:8888/borinud/api/v1/dbajson/*/*/*/*/*/*/summaries/2020/12/09
Dovrebbe restituire dei risultati, infatti ci sono dei dati 
http://18.195.7.150:8888/showdata/*/*/*/254,0,0/103,2000,-,-/B12101/spatialseries/2020/12/09?dsn=report

**Comment by pat1** [comment]
come detto sopra dipende da
https://github.com/ARPA-SIMC/dballe/issues/242
in attesa di pacchettizzazione

**Comment by pat1** [comment]
la quale pacchettizzazione dipende da:
https://github.com/ARPA-SIMC/dballe/issues/241

**Comment by pat1** [comment]
nuovi pacchetti disponibili.
dopo aver effettuato un dnf upgrade tutto dovrebbe funzionare.

**Comment by pat1** [comment]
ho testato anche le estensioni a borinud e paiono funzionare:

https://test.rmap.cc/borinud/api/v1/dbajson/*/*/fixed/254,0,0/103,2000,-,-/B12101/summaries/2020/12/15?latmin=4512345&latmax=4612345&lonmin=1212345&lonmax=1312345

contro

https://test.rmap.cc/borinud/api/v1/dbajson/*/*/fixed/254,0,0/103,2000,-,-/B12101/summaries/2020/12/15

lascio aperta issue per permettere ulteriori verifiche a @gianpieropa

**Comment by pat1** [comment]
pare ci siano in station e stationdata alcuni problemi con il fattore di scala delle coordinate

**Comment by pat1** [comment]
risolti, nuvo pacchetto python3-rmap disponibile

**Comment by pat1** [comment]
funziona il tutto ?
si può chiudere la issue ?

**Comment by gianpieropa** [comment]
Si
