### ISSUE TITLE
Errore timerange su skinny

### ISSUE THREAD

**Issue by fabiodepas** [ARPA-SIMC/cosudo#71]
Le date non  sembrano essere corrette, bisogna rivedere i timerange e se il problema è  relativo la versione forkata  di skinnywms o  da una nostra gestione errata (esempio parametro utilizzato errato)

**Comment by gianpieropa** [comment]
Confermo sia un problema della versione di cui abbiamo fatto il fork. Sul branch master le date vengono gestite correttamente.

**Comment by gianpieropa** [comment]
Solved  gianpieropa/skinnywms#3
