### ISSUE TITLE
aggiungere i test a radarconverter

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/cosudo#78]
ci sono i dati (netcdf) per fare i test di conversione avanti e indietro ...

**Comment by fabiodepas** [comment]
Inserite funzioni di test, naturalmente non abbiamo caricato i file (grib e netcdf) utilizzati per i test su git, 
la funzione di verifica dei gri vaabuonfine sututti i file,
la funzione per la verifica dei netcdf invece fallisce,
difatti partendo da un netcdf e convertendolo in grib non ci sono problemi, 
quando si esegue l'operazione al contrario alcune informazioni come la divisione in intervalli di lat e lon, 
non essendo presente nei grib, va fatta a mano, 
questo introduce delle differenze dovute agli arrotondamenti, si parla di arrotondamenti alla 4-5 cifra decimale, 
ma in sostanza questo impedisce di dimostrare che il contenuto dei file è identico. 
Avreste gentilmente consiglio o la buona  conversione con ritorno dei grib risulta sufficiente?
Ancheperchèameno delle ultime  cifre  decimali il dump ed  il render grafico dei file sembrano  essere uguali.

**Comment by fabiodepas** [comment]
Modifcata  la funzione di  test er laverifica  dei netcdf, se i file non sono "identici"  calcoliamo l'errore su latitudini, longitudini e dati e se non supera la soglia di 0.0005 allora lo diamo per buono.
