### ISSUE TITLE
Dowload GRIB arkimet con API python

### ISSUE THREAD

**Issue by fabiodepas** [ARPA-SIMC/cosudo#8]
Per il servizio WMS i dati in formato GRIB saranno gestiti mediante Arkimet, come da capitolato si  richiede che:
"L’accesso ai dati dovrà essere realizzato tramite API python del pacchetto python descritte a https://arpa-simc.github.io/arkimet/python/index.html".
Nella descrizione della funzione "query_data" (https://arpa-simc.github.io/arkimet/python/arkimet.dataset.html#) vi è un modo per scaricare il grib risultante dalla query come nelle api web (es. http://127.0.0.1:8080/query?query=reftime:%3E=2005&style=data)?

**Comment by edigiacomo** [comment]
```python
import arkimet
arki_base_url = "http://arkimet-server:8090"
dataset_name = "dataset_name"

sections = arkimet.dataset.http.load_cfg_sections(arki_base_url) 
reader = arkimet.dataset.Reader(sections[dataset_name])
with open("result.grib", "wb") as fp:
    reader.query_bytes("reftime:=2005", file=fp)
```

Al posto di un file si può usare qualsiasi oggetto file-like (o altro, si veda https://arpa-simc.github.io/arkimet/python/arkimet.dataset.html#arkimet.dataset.Reader.query_bytes)

**Comment by fabiodepas** [comment]
Perfetto non ci era  chiaro se il formato restituito dalla funzione "query_bytes"  fosse un grib. Grazie
