### ISSUE TITLE
Mapserver info DEM

### ISSUE THREAD

**Issue by fabiodepas** [ARPA-SIMC/cosudo#82]
Salve, stiamo cercando di  visualizzare "correttamente" il dem, ma questo risulta spostato  sulla mappa,cambiando i valori delle x e delle y nel file hdr riusciamo a posizionarlo nel punto giusto sulla mappa  ed anche la  dimensione sembra esatta, dato che nemmeno gdal riesce a dirci  l'esatta proiezione di riferimento, avete idee o consigli? o potrebbe essere che il file hdr è stato modificato? Grazie

**Comment by PasqualiSIMC** [comment]
Buongiorno, il dem è UTM32n WGS84 nell'HDR è indicata qual'è la prima cella (yll = lower left)

**Comment by fabiodepas** [comment]
Perfetto orasi  vede nel punto giusto. MapServer continuava ad utilizzare UTM33, quindi il codice della proiezione è epsg:32632
Grazie mille.
