### ISSUE TITLE
conversione di unità di misura nei grafici

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/cosudo#85]
la temperatura su mappa viene visualizzata in °C , nel grafico in K.

oltre a questa schizzofrenia mi chiedo come venga fatta la conversione tra unità di misura come sia gestibile nel backend

**Comment by gianpieropa** [comment]
La gestione è fatta come in showdata, c'è un file js chiamato borinud.B.js con una map col seguente formato: 
````
"B11002": {
            "description": "WIND SPEED",
            "unit": "M/S",
            "scale": 1,
            "offset": 0
        },
````

**Comment by gianpieropa** [comment]
Provvedo a sistemare il bug nella rappresentazione su grafico
