### ISSUE TITLE
dati su mappa visualizzati come NaN

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/cosudo#86]
molti dati su mappa vengono rappresentati come NaN.
pare corrisponda a valori non rappresentabili nel formato prestabilito

ad esempio:
selezionare rete "fidu" e var "Pressure"

**Comment by pat1** [comment]
il problema persiste ad esempio con la pressione

**Comment by gianpieropa** [comment]
Ho ritentato in locale  e sembra funzionare. Ho provato a comparare i testi del file map-view.js, e quello su test.rmap.cc è diverso da quello attuale, mentre i file html sono quelli dell'ultima versione

**Comment by pat1** [comment]
si, scusa, mi sono dimenticato di aggiornare gli static files
