### ISSUE TITLE
modifica estensione temporale nei Grafici

### ISSUE THREAD

**Issue by PasqualiSIMC** [ARPA-SIMC/cosudo#97]
l’estensione temporale del grafico dovrebbe essere anche indipendente dall’estensione temporale della mappa

**Comment by gianpieropa** [comment]
La ricerca dei dati da visualizzare su grafico e quella su mappa, sono già separate. Si possono selezionare date diverse su mappa e su grafico

**Comment by PasqualiSIMC** [comment]
Intendevamo dire che il grafico deve poter visualizzare più giorni contemporaneamente

**Comment by pat1** [comment]
riusciamo a chiarire questa issue ?
Io il problema lo vedo così:
nella sezione grafici una volta aggiunti dati al grafico non è più possibile modificare gli estremi temporali dei dati aggiunti.
Ogni gruppo di dati aggiunti ha un estremo temporale indipendente.
Questa potrebbe essere considerata un feature, ma di fatto non lo è.
Quello che è utile è decidere quali dati avere nel grafico (indipendentemente dal range temporale) e poi poter navigare la visualizzazione del grafico nel tempo sia come range che come posizionamento temporale; range è posizione nel tempo possono (devono) essere univoci per tutti i parametri nello stesso grafico

**Comment by gianpieropa** [comment]
Quindi credo sia risolvibile aggiungendo invece che la ricerca per singola data la ricerca con range temporale, utilizzando le estensioni delle API di borinud (daymax,daymin ecc...) e separandola dalla selezione delle variabili (bcode, timerange, level..). Quindi in questo modo bisognerebbe effettuare due step per visualizzare il grafico: il primo step è l'aggiunta delle variabili al grafico (l'insieme di bocde timerange, level ecc..) e poi come secondo step selezionare le date di riferimento ed effettuare la ricerca. Procedo cosi?

**Comment by PasqualiSIMC** [comment]
Con riferimento all'issue #118 se la vista grafici e la vista mappa non hanno nessun punto di contatto allora si può procedere come dice Giampiero, rimane l'assenza di uno strumento che a partire dalla visualizzazione spaziale, fissato un punto, generi la vista temporale. Se vediamo la vista temporale (grafici) in quest'ultimo modo, allora bcode, timerange ,level etc. vengono ereditati dalla mappa e occorre solo rifare la richiesta dati con una estensione temporale diversa

**Comment by gianpieropa** [comment]
Come indicato nella #118 il punto di contatto è il bottone "add to graph" presente nel popup del dato. Al momento tale bottone aggiunge al grafico una ricerca con anche la data, ma data la modifica che apporterò per avere un range temporale con le variabili separate, il nuovo funzionamento risulterà in un'aggiunta di solo le variabili (bcode, timerange ,level, network, lat lon). In questo modo dovrebbe rispettare il funzionamento voluto. Procedo ad effettuare tali modifiche

**Comment by gianpieropa** [comment]
Sto procedendo ad effettuare il push spiego qui in breve come funziona la vista grafico:
Dalla parte a sinistra (quella di ricerca) si aggiungono le variabili che saranno visualizzate nella tabella a sinistra in basso. L'orario della barra di ricerca serve solamente a controllare quali combinazioni sono esistenti. Una volta aggiunte le variabili, a destra abbiamo il selettore del range temporale con accanto un bottone di ricerca. Effettuata la ricerca in basso al grafico avremo la solita legenda, che suddivide il tutto per lat_lon,network, ident  e timerange. Ho aggiunto anche il bottone "Load" nella colona del nome per effettuare la ricerca, nel caso non trovi nulla apparirà la scritta "Not found" come nell'immagine qui sotto(come da #98 )
![Schermata del 2021-05-26 17-41-03](https://user-images.githubusercontent.com/68102511/119690842-53ef9680-be4a-11eb-9672-d6f06f5cd13f.png)
