### ISSUE TITLE
visualizzazione dati costanti di stazione nella legenda del grafico

### ISSUE THREAD

**Issue by PasqualiSIMC** [ARPA-SIMC/cosudo#98]
sul grafico non è presente il nome/legenda che identifichi le stazioni presenti

**Comment by gianpieropa** [comment]
La legenda è presente.
![Schermata del 2021-02-18 10-18-57](https://user-images.githubusercontent.com/68102511/108335009-ccebac00-71d2-11eb-87b0-c1fa7c0be066.png)

**Comment by PasqualiSIMC** [comment]
manca il nome stazione e il network di appartenenza

**Comment by gianpieropa** [comment]
Il network dovrebbe essere presente, per esempio nell'immagine sopra è "dpcn-bolzanoboze". Il nome stazione non dovrebbe essere l'ident?

**Comment by PasqualiSIMC** [comment]
L'ident è l'utente che si è registrato, il nome di stazione è solitamente
la località dove la stazione è posta: Parma, Sant'Agata Bolognese,
Marzaglia etc


Andrea Pasquali
ARPAE - SIMC
Viale Silvani, 6
CAP 40122 BOLOGNA
ITALIA
Tel. +39-0516497566
Cell. +39-3314009732
E-mail a ***@***.******@***.***
web site www.arpae.it/sim


Il giorno lun 24 mag 2021 alle ore 09:29 gianpieropa <
***@***.***> ha scritto:

**Comment by gianpieropa** [comment]
Non credo sia presente come informazione all'interno delle risposte di borinud, chiedo conferma a @pat1

**Comment by pat1** [comment]
la richiesta è in relazione a #120 #121 e #122
Gli utenti chiedono di avere le informazioni della "vista" "costant station data" insieme alla vista "dati".
Non so come sia realizzabile.

**Comment by gianpieropa** [comment]
Le uniche cose che mettono in relazione i dati con le stazioni credo siano solo l'ident e la latitudine/longitudine, non so se siano abbastanza come informazioni per collegarli. E anche se fossero sufficienti ci sarebbe una riduzione delle prestazioni molto evidente, in quanto bisognerebbe richiedere tutte le stazioni, tutti i dati costanti, collegare questi in un oggetto e per ogni dato proveniente da borinud accedere a questo oggetto e ripescare le informazioni necessarie.

**Comment by pat1** [comment]
il collegamento avviene tramite ident lat lon e network.
Bisognerebbe provare quanto è pesante una richiesta ajax a costant station data solo per una singola  ident lat lon e network
attivata su richiesta dell'utente.
Mi pare abbastanza prestante:
https://test.rmap.cc/borinud/api/v1/dbajson/-/1101250,4447409/fidu/*/*/B01019/stationdata?dsn=report_fixed
e ottengo il nome stazione

**Comment by gianpieropa** [comment]
Si potremmo procedere in questo modo e quindi con un bottone al click dell'utente richiedere le informazioni  delle stazioni e visualizzarle. Ditemi se va bene e procedo

**Comment by PasqualiSIMC** [comment]
Si per me va bene

**Comment by PasqualiSIMC** [comment]
Vorremmo il nome e l'id stazione elencati nella legenda senza dover cliccare, in automatico con la visualizzazione del grafico. Capiamo che attualmente non è facile ottenerlo

**Comment by pat1** [comment]
ripeto che l'id stazione NON esiste
